/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.smartmed.client;

/**
 *
 * @author anukratimehta
 */
import com.healthcare.grpc.consultation.*;
import com.healthcare.grpc.diagnostic.*;
import com.healthcare.grpc.monitoring.*;
import com.healthcare.grpc.patient.*;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.stub.StreamObserver;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

public class SmartMedGUI extends javax.swing.JFrame {

    private ManagedChannel channel;

    public SmartMedGUI() {
        initComponents();
        initializeGRPCChannel();
        idField.requestFocusInWindow();
    }

    private void initializeGRPCChannel() {
        this.channel = ManagedChannelBuilder.forAddress("localhost", 50051)
                .usePlaintext()
                .build();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientBtn = new javax.swing.JButton();
        monitoringBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        diagnosticBtn = new javax.swing.JButton();
        consultationBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientBtn.setText("Patient Records");
        patientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBtnActionPerformed(evt);
            }
        });

        monitoringBtn.setText("Monitor Vitals");
        monitoringBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitoringBtnActionPerformed(evt);
            }
        });

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        diagnosticBtn.setText("Upload Image");

        consultationBtn.setText("LiveConsultation");

        jLabel1.setText("Patient Id:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(diagnosticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consultationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monitoringBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(idField))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monitoringBtn)
                    .addComponent(patientBtn))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultationBtn)
                    .addComponent(diagnosticBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log(String message) {
        resultArea.append(message + "\n");
        resultArea.setCaretPosition(resultArea.getDocument().getLength());
    }

    private void patientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBtnActionPerformed
        // TODO add your handling code here:
        String patientId = idField.getText().trim();

        // Input validation
        try {
            int id = Integer.parseInt(patientId);
            if (id < 1 || id > 100) {
                log("\nError: Patient ID must be between 1-100");
                return;
            }
        } catch (NumberFormatException e) {
            log("\nError: Please enter a number 1-100");
            return;
        }

        new Thread(() -> {
            try {
                log("\nFetching record for patient: " + patientId);

                PatientResponse response = PatientServiceGrpc.newBlockingStub(channel)
                        .getPatientRecord(PatientRequest.newBuilder()
                                .setPatientId(patientId)
                                .build());

                // Display REAL response from server
                log("Name: " + response.getName());
                log("Medication: " + response.getCurrentMedication());
                log("History: " + response.getMedicalHistoryList());

            } catch (Exception e) {
                log("Error: " + e.getMessage());
            }
        }).start();
    }//GEN-LAST:event_patientBtnActionPerformed

    private void monitoringBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitoringBtnActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                log("\n=== Starting Vitals Monitoring ===");
                CountDownLatch latch = new CountDownLatch(1);

                MonitoringServiceGrpc.MonitoringServiceStub stub
                        = MonitoringServiceGrpc.newStub(channel);

                stub.streamVitals(
                        VitalsRequest.newBuilder()
                                .setPatientId("patient-123")
                                .setDurationSeconds(10) // Monitor for 10 seconds
                                .build(),
                        new StreamObserver<VitalsUpdate>() {
                    @Override
                    public void onNext(VitalsUpdate update) {
                        log(String.format("Heart Rate: %d | Oxygen: %.1f%% | Time: %tT",
                                update.getHeartRate(),
                                update.getOxygenLevel(),
                                update.getTimestamp()));
                    }

                    @Override
                    public void onError(Throwable t) {
                        log("Monitoring error: " + t.getMessage());
                        latch.countDown();
                    }

                    @Override
                    public void onCompleted() {
                        log("Monitoring session ended");
                        latch.countDown();
                    }
                });

                latch.await();
            } catch (Exception ex) {
                log("Error in vitals monitoring: " + ex.getMessage());
            }
        }).start();
    }//GEN-LAST:event_monitoringBtnActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
        String patientId = idField.getText().trim();

    // Client-side validation
    try {
        int idNum = Integer.parseInt(patientId);
        if (idNum < 1 || idNum > 100) {
            log("\nError: Patient ID must be between 1-100");
            return;
        }
    } catch (NumberFormatException e) {
        log("\nError: Patient ID must be a number (1-100)");
        return;
    }

    new Thread(() -> {
        try {
            log("\n=== Fetching Record for Patient: " + patientId + " ===");
            PatientServiceGrpc.PatientServiceBlockingStub stub = 
                PatientServiceGrpc.newBlockingStub(channel);

            // Get response from server (no client-side generation)
            PatientResponse response = stub.getPatientRecord(
                PatientRequest.newBuilder()
                    .setPatientId(patientId)
                    .build());

            // Server will always return a valid response or error
            log("Patient ID: " + response.getPatientId());
            log("Name: " + response.getName());
            log("Current Medication: " + response.getCurrentMedication());
            log("Medical History: " + response.getMedicalHistoryList());
            
        } catch (io.grpc.StatusRuntimeException e) {
            log("Server Error: " + e.getStatus().getDescription());
        } catch (Exception ex) {
            log("Error: " + ex.getMessage());
        }
    }).start();
    }//GEN-LAST:event_idFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(SmartMedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartMedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartMedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartMedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartMedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartMedGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultationBtn;
    private javax.swing.JButton diagnosticBtn;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton monitoringBtn;
    private javax.swing.JButton patientBtn;
    private javax.swing.JTextArea resultArea;
    // End of variables declaration//GEN-END:variables
}
